const dummyProperties = [
    {
        id: 'uuid3',
        user_id: 'user_uuid3',
        title: 'Cozy Cottage',
        description: 'A quaint cottage in the woods.',
        price: 180000.00,
        type: 'Residential',
        address: '789 Country Rd',
        zipcode: '54321',
        city: 'Austin',
        latitude: 30.267153,
        longitude: -97.743057,
        bedrooms: 2,
        washrooms: 1,
        area: 800.00,
        furnished: true,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: true,
        status: 'New',
        category: 'Cottage',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid4',
        user_id: 'user_uuid4',
        title: 'Modern Loft',
        description: 'Stylish loft in the heart of the city.',
        price: 350000.00,
        type: 'Residential',
        address: '101 Urban Ave',
        zipcode: '67890',
        city: 'Chicago',
        latitude: 41.878113,
        longitude: -87.629799,
        bedrooms: 1,
        washrooms: 1,
        area: 900.00,
        furnished: false,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: false,
        status: 'Conflict',
        category: 'Loft',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid5',
        user_id: 'user_uuid5',
        title: 'Beachfront Property',
        description: 'A stunning property right on the beach.',
        price: 750000.00,
        type: 'Residential',
        address: '234 Ocean Dr',
        zipcode: '90210',
        city: 'Miami',
        latitude: 25.7617,
        longitude: -80.1918,
        bedrooms: 4,
        washrooms: 3,
        area: 2000.00,
        furnished: true,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: true,
        status: 'Notice',
        category: 'House',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid6',
        user_id: 'user_uuid6',
        title: 'Suburban Family Home',
        description: 'Perfect for families looking for space.',
        price: 320000.00,
        type: 'Residential',
        address: '456 Maple St',
        zipcode: '11223',
        city: 'Seattle',
        latitude: 47.606209,
        longitude: -122.332071,
        bedrooms: 3,
        washrooms: 2,
        area: 1500.00,
        furnished: false,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: true,
        status: 'InProgress',
        category: 'House',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid7',
        user_id: 'user_uuid7',
        title: 'Downtown Office Space',
        description: 'Ideal for startups and small businesses.',
        price: 600000.00,
        type: 'Commercial',
        address: '888 Business Blvd',
        zipcode: '60601',
        city: 'San Francisco',
        latitude: 37.774929,
        longitude: -122.419418,
        bedrooms: 0,
        washrooms: 2,
        area: 2500.00,
        furnished: false,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: false,
        status: 'Dis-Conn',
        category: 'Office',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid8',
        user_id: 'user_uuid8',
        title: 'Renovated Warehouse',
        description: 'Converted warehouse into living space.',
        price: 450000.00,
        type: 'Residential',
        address: '500 Industrial Rd',
        zipcode: '94103',
        city: 'San Diego',
        latitude: 32.715736,
        longitude: -117.161087,
        bedrooms: 2,
        washrooms: 2,
        area: 1800.00,
        furnished: true,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: true,
        status: 'New',
        category: 'Warehouse',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid9',
        user_id: 'user_uuid9',
        title: 'Office in Tech Hub',
        description: 'Located in the heart of the tech district.',
        price: 550000.00,
        type: 'Commercial',
        address: '333 Tech St',
        zipcode: '94107',
        city: 'Austin',
        latitude: 30.267153,
        longitude: -97.743057,
        bedrooms: 0,
        washrooms: 1,
        area: 1500.00,
        furnished: false,
        kitchen: false,
        water: true,
        electricity: true,
        IsPaid: false,
        status: 'Conflict',
        category: 'Office',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid10',
        user_id: 'user_uuid10',
        title: 'Rural Farmhouse',
        description: 'A peaceful farmhouse with lots of land.',
        price: 300000.00,
        type: 'Residential',
        address: '222 Farm Rd',
        zipcode: '12345',
        city: 'Nashville',
        latitude: 36.162664,
        longitude: -86.781602,
        bedrooms: 3,
        washrooms: 1,
        area: 2200.00,
        furnished: true,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: true,
        status: 'Notice',
        category: 'Farmhouse',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid11',
        user_id: 'user_uuid11',
        title: 'Penthouse Suite',
        description: 'Luxurious penthouse with skyline views.',
        price: 1200000.00,
        type: 'Residential',
        address: '999 Sky High Ave',
        zipcode: '10001',
        city: 'New York',
        latitude: 40.712776,
        longitude: -74.005974,
        bedrooms: 3,
        washrooms: 3,
        area: 2500.00,
        furnished: true,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: false,
        status: 'InProgress',
        category: 'Penthouse',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid12',
        user_id: 'user_uuid12',
        title: 'Charming Bungalow',
        description: 'A lovely bungalow in a quiet neighborhood.',
        price: 220000.00,
        type: 'Residential',
        address: '321 Quiet St',
        zipcode: '90210',
        city: 'Los Angeles',
        latitude: 34.052235,
        longitude: -118.243683,
        bedrooms: 2,
        washrooms: 1,
        area: 950.00,
        furnished: true,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: true,
        status: 'Conflict',
        category: 'Bungalow',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid13',
        user_id: 'user_uuid13',
        title: 'High-End Retail Space',
        description: 'Prime location for retail business.',
        price: 800000.00,
        type: 'Commercial',
        address: '300 Fashion St',
        zipcode: '60610',
        city: 'Chicago',
        latitude: 41.878113,
        longitude: -87.629799,
        bedrooms: 0,
        washrooms: 1,
        area: 2000.00,
        furnished: false,
        kitchen: false,
        water: true,
        electricity: true,
        IsPaid: true,
        status: 'New',
        category: 'Retail',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid14',
        user_id: 'user_uuid14',
        title: 'Eco-Friendly Home',
        description: 'Sustainable home with solar panels.',
        price: 350000.00,
        type: 'Residential',
        address: '77 Greenway Ln',
        zipcode: '30301',
        city: 'Atlanta',
        latitude: 33.7490,
        longitude: -84.3880,
        bedrooms: 3,
        washrooms: 2,
        area: 1500.00,
        furnished: true,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: false,
        status: 'Dis-Conn',
        category: 'House',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid15',
        user_id: 'user_uuid15',
        title: 'Art Studio Space',
        description: 'Bright and spacious studio for artists.',
        price: 250000.00,
        type: 'Commercial',
        address: '12 Art Lane',
        zipcode: '33101',
        city: 'Miami',
        latitude: 25.7617,
        longitude: -80.1918,
        bedrooms: 0,
        washrooms: 1,
        area: 1200.00,
        furnished: false,
        kitchen: false,
        water: true,
        electricity: true,
        IsPaid: true,
        status: 'InProgress',
        category: 'Studio',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid16',
        user_id: 'user_uuid16',
        title: 'Luxury Villa',
        description: 'A magnificent villa with a pool.',
        price: 950000.00,
        type: 'Residential',
        address: '88 Paradise Blvd',
        zipcode: '90210',
        city: 'Beverly Hills',
        latitude: 34.0901,
        longitude: -118.4065,
        bedrooms: 5,
        washrooms: 4,
        area: 4000.00,
        furnished: true,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: true,
        status: 'Notice',
        category: 'Villa',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid17',
        user_id: 'user_uuid17',
        title: 'Historic Building',
        description: 'A preserved historic building with character.',
        price: 600000.00,
        type: 'Commercial',
        address: '15 Heritage Rd',
        zipcode: '60611',
        city: 'Chicago',
        latitude: 41.878113,
        longitude: -87.629799,
        bedrooms: 0,
        washrooms: 2,
        area: 3000.00,
        furnished: false,
        kitchen: false,
        water: true,
        electricity: true,
        IsPaid: false,
        status: 'Conflict',
        category: 'Commercial',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid18',
        user_id: 'user_uuid18',
        title: 'City Center Apartment',
        description: 'Modern apartment in the city center.',
        price: 400000.00,
        type: 'Residential',
        address: '99 City Plaza',
        zipcode: '10010',
        city: 'New York',
        latitude: 40.712776,
        longitude: -74.005974,
        bedrooms: 2,
        washrooms: 2,
        area: 1100.00,
        furnished: true,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: true,
        status: 'New',
        category: 'Apartment',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid19',
        user_id: 'user_uuid19',
        title: 'Tech Startup Office',
        description: 'Creative space for tech startups.',
        price: 500000.00,
        type: 'Commercial',
        address: '202 Innovation Way',
        zipcode: '94105',
        city: 'San Francisco',
        latitude: 37.774929,
        longitude: -122.419418,
        bedrooms: 0,
        washrooms: 1,
        area: 1600.00,
        furnished: false,
        kitchen: false,
        water: true,
        electricity: true,
        IsPaid: false,
        status: 'InProgress',
        category: 'Office',
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        id: 'uuid20',
        user_id: 'user_uuid20',
        title: 'Spacious Townhouse',
        description: 'A lovely townhouse with modern amenities.',
        price: 370000.00,
        type: 'Residential',
        address: '234 Town St',
        zipcode: '30303',
        city: 'Atlanta',
        latitude: 33.7490,
        longitude: -84.3880,
        bedrooms: 3,
        washrooms: 2,
        area: 1800.00,
        furnished: true,
        kitchen: true,
        water: true,
        electricity: true,
        IsPaid: true,
        status: 'Notice',
        category: 'Townhouse',
        created_at: new Date(),
        updated_at: new Date()
    },
];

export default dummyProperties;